const translations = {
  ja: {
    pageTitle: "にし田ホルモン | 京都の新鮮ホルモン・焼肉用お肉専門店",
    metaDescription:
      "京都市上京区のにし田ホルモン。新鮮な牛ホルモン、焼肉用の牛肉、BBQ向けの牛肉カットを扱う地域密着型の精肉店。",
    metaOgDescription: "京都の新鮮ホルモン・焼肉用お肉専門店。",
    brandAria: "にし田ホルモン トップ",
    navAria: "メインナビゲーション",
    navAbout: "お店について",
    navMeat: "お肉",
    navPrices: "価格",
    navAccess: "アクセス",
    languageLabel: "言語",
    languageAria: "言語を選択",
    callShort: "電話",
    heroAlt: "にし田ホルモンの焼肉用お肉とホルモンのショーケース",
    heroKicker: "京都・上京区の精肉店",
    heroTitle: "京都の新鮮ホルモン・焼肉用お肉専門店",
    heroSubtitle: "Fresh Japanese meat and horumon in Kyoto",
    heroCopy: "焼肉、BBQ、ご家庭の料理に。新鮮なお肉を丁寧にご用意しています。",
    callNow: "電話する",
    viewInstagram: "Instagramを見る",
    viewMaps: "Google Mapsで見る",
    storeInfoAria: "店舗情報",
    hoursLabel: "営業時間",
    holidayLabel: "定休日",
    holidayValue: "定休日なし",
    stationLabel: "最寄り",
    stationValue: "円町駅から徒歩圏内",
    quickAria: "クイック連絡先",
    quickPhoneLabel: "電話",
    quickAddressLabel: "住所",
    addressShort: "京都市上京区 下之町400",
    aboutKicker: "お店について",
    aboutTitle: "地域に根ざした、頼れるお肉屋さん。",
    aboutText:
      "にし田ホルモンは、京都市上京区にある地域密着型の精肉店です。新鮮なホルモン、焼肉用のお肉、家庭料理に使いやすいお肉を丁寧にご用意しています。",
    trustFresh: "新鮮なお肉",
    trustLocal: "京都の地域店",
    trustYakiniku: "焼肉・BBQ対応",
    storefrontAlt: "京都の精肉店の外観イメージ",
    showcaseAlt: "お肉のショーケース",
    recommendedAria: "本日のおすすめ",
    bbqAlt: "BBQと焼肉に合うお肉セット",
    dailyKicker: "本日のおすすめ",
    dailyTitle: "迷ったら、人数と用途を伝えてください。",
    dailyText:
      "BBQ、焼肉、鍋、ご家庭の夕食など、人数や食べ方に合わせておすすめを相談できます。仕入れ状況により内容は変わります。",
    askStock: "在庫を確認する",
    meatKicker: "取扱い商品",
    meatTitle: "牛肉とホルモンを、焼肉でおいしく。",
    horumonAlt: "ホルモン盛り合わせ",
    beefAlt: "牛肉の焼肉用カット",
    yorosuAlt: "ヨロス",
    techanAlt: "テッチャン",
    hosotechanAlt: "細テッチャン",
    coricoriAlt: "コリコリ",
    haramiAlt: "ハラミ",
    baraAlt: "バラ",
    cardHorumonTitle: "ホルモン",
    cardHorumonText: "焼肉や鍋に使いやすい、新鮮なホルモン各種。",
    cardBeefTitle: "牛肉",
    cardBeefText: "カルビ、ハラミ、タンなど焼肉に合う部位。",
    cardYorosuTitle: "ヨロス",
    cardYorosuText: "焼肉で楽しめる、食感のある牛ホルモン系カット。",
    cardTechanTitle: "テッチャン",
    cardTechanText: "脂の旨みと噛みごたえが魅力の定番ホルモン。",
    cardHosotechanTitle: "細テッチャン",
    cardHosotechanText: "焼きやすく、香ばしさを楽しめる細めのホルモン。",
    cardCoricoriTitle: "コリコリ",
    cardCoricoriText: "名前の通り、歯切れのよい食感が楽しめる部位。",
    cardHaramiTitle: "ハラミ",
    cardHaramiText: "旨みが濃く、焼肉で人気の高い牛ハラミ。",
    cardBaraTitle: "バラ",
    cardBaraText: "脂の甘みと肉の旨みを楽しめる焼肉向けカット。",
    priceSpace: "価格記入欄あり",
    askStore: "店頭で確認",
    priceKicker: "価格",
    priceTitle: "Precios aproximados / 価格",
    priceIntro: "価格欄は編集用です。公開前に正確な価格を入力してください。",
    priceAria: "価格表",
    priceYorosu: "ヨロス",
    priceTechan: "テッチャン",
    priceHosotechan: "細テッチャン",
    priceCoricori: "コリコリ",
    priceHarami: "ハラミ",
    priceBara: "バラ",
    priceNotice:
      "価格は仕入れ状況により変更となる場合があります。詳しくは店舗までお問い合わせください。",
    servicesKicker: "サービス",
    servicesTitle: "買いやすく、相談しやすく。",
    serviceFresh: "新鮮なお肉の販売",
    serviceYakiniku: "焼肉用カット",
    serviceBbq: "BBQ用の準備",
    servicePeople: "人数に合わせたおすすめ",
    servicePhone: "電話での問い合わせ",
    serviceStock: "在庫確認",
    serviceStore: "店頭での相談",
    serviceInstagram: "Instagramで日々の情報",
    paymentKicker: "お支払い方法",
    paymentTitle: "公開前に確認が必要な項目です。",
    paymentText:
      "現金以外の支払い方法は、公開前に店舗へ確認してください。未確認の方法は確定情報として掲載しません。",
    cash: "現金",
    confirmed: "確認済みとして掲載可能",
    card: "カード",
    confirmBefore: "公開前に確認",
    paypay: "PayPay / QR",
    otherPayment: "その他",
    galleryKicker: "写真",
    galleryTitle: "商品が伝わる、きれいなビジュアル。",
    galleryText:
      "現在はWeb用に生成したビジュアルを使用しています。公開時は店舗の実写真や許可済みのInstagram写真に差し替えできます。",
    gallery1Alt: "ショーケースに並ぶ焼肉用の肉",
    gallery2Alt: "ホルモンの盛り合わせ",
    gallery3Alt: "牛肉の焼肉用カット",
    gallery4Alt: "BBQセット",
    gallery5Alt: "京都の店舗イメージ",
    gallery6Alt: "精肉店のショーケース",
    howKicker: "買い方",
    howTitle: "初めてでも簡単に相談できます。",
    step1Title: "用途を決める",
    step1Text: "焼肉、BBQ、鍋、夕食など。",
    step2Title: "人数を伝える",
    step2Text: "必要な量を相談しやすくなります。",
    step3Title: "在庫を確認",
    step3Text: "電話または店頭で確認できます。",
    step4Title: "受け取り",
    step4Text: "店頭で新鮮なお肉を受け取ります。",
    accessKicker: "アクセス",
    accessTitle: "円町駅から徒歩圏内。",
    accessText:
      "京都市上京区丸太町御前東入る下之町400。近くに来たらGoogle Mapsで現在地から確認できます。",
    addressLabel: "住所",
    mapTitle: "Google Maps - にし田ホルモン",
    faqKicker: "よくある質問",
    faqTitle: "来店前に知っておきたいこと。",
    faq1Q: "予約や取り置きはできますか？",
    faq1A: "在庫状況により異なります。電話で店舗へお問い合わせください。",
    faq2Q: "観光客でも買えますか？",
    faq2A: "はい。焼肉、BBQ、自炊用など用途を伝えると相談しやすいです。",
    faq3Q: "価格はいつも同じですか？",
    faq3A: "仕入れ状況により変わる場合があります。詳しくは店頭または電話で確認してください。",
    contactKicker: "お問い合わせ",
    contactTitle: "来店前の確認もお気軽に。",
    telLabel: "電話",
    openInstagram: "Instagramを開く",
    openMaps: "Google Mapsを開く",
    floatingAria: "固定クイックアクション",
    floatCall: "電話",
    footerSeo: "京都 ホルモン・焼肉用お肉・上京区の精肉店。",
    backTop: "トップへ",
  },
  es: {
    pageTitle: "Nishida Horumon | Carnicería japonesa en Kyoto",
    metaDescription:
      "Nishida Horumon en Kamigyo-ku, Kyoto. Carnicería japonesa especializada en res, horumon fresco y cortes para yakiniku o BBQ.",
    metaOgDescription: "Carne japonesa fresca y horumon en Kyoto.",
    brandAria: "Inicio de Nishida Horumon",
    navAria: "Navegación principal",
    navAbout: "Sobre nosotros",
    navMeat: "Carnes",
    navPrices: "Precios",
    navAccess: "Ubicación",
    languageLabel: "Idioma",
    languageAria: "Seleccionar idioma",
    callShort: "Llamar",
    heroAlt: "Mostrador con carne para yakiniku y horumon de Nishida Horumon",
    heroKicker: "Carnicería en Kamigyo, Kyoto",
    heroTitle: "Carnes frescas y horumon para yakiniku en Kyoto",
    heroSubtitle: "Fresh Japanese meat and horumon in Kyoto",
    heroCopy: "Para yakiniku, BBQ y cocina en casa. Cortes frescos preparados con cuidado.",
    callNow: "Llamar ahora",
    viewInstagram: "Ver Instagram",
    viewMaps: "Ver ubicación",
    storeInfoAria: "Información de la tienda",
    hoursLabel: "Horario",
    holidayLabel: "Descanso",
    holidayValue: "Sin día fijo de descanso",
    stationLabel: "Cerca de",
    stationValue: "A distancia caminable de Emmachi Station",
    quickAria: "Contacto rápido",
    quickPhoneLabel: "Teléfono",
    quickAddressLabel: "Dirección",
    addressShort: "Kamigyo-ku, Kyoto, Shimonochō 400",
    aboutKicker: "Sobre nosotros",
    aboutTitle: "Una carnicería local cercana y confiable.",
    aboutText:
      "Nishida Horumon es una carnicería local en Kamigyo-ku, Kyoto. Prepara con cuidado horumon fresco, carnes para yakiniku y cortes prácticos para la cocina familiar.",
    trustFresh: "Carne fresca",
    trustLocal: "Tienda local en Kyoto",
    trustYakiniku: "Yakiniku y BBQ",
    storefrontAlt: "Imagen de una carnicería en Kyoto",
    showcaseAlt: "Mostrador de carnes",
    recommendedAria: "Producto recomendado del día",
    bbqAlt: "Set de carne para BBQ y yakiniku",
    dailyKicker: "Recomendado del día",
    dailyTitle: "Si no sabes qué comprar, di cuántas personas son y para qué ocasión.",
    dailyText:
      "Puedes consultar recomendaciones para BBQ, yakiniku, nabe o cena en casa. La disponibilidad cambia según el abastecimiento.",
    askStock: "Consultar disponibilidad",
    meatKicker: "Productos",
    meatTitle: "Cortes de res y horumon para disfrutar en yakiniku.",
    horumonAlt: "Surtido de horumon",
    beefAlt: "Cortes de res para yakiniku",
    yorosuAlt: "Yorosu",
    techanAlt: "Techan",
    hosotechanAlt: "Hosotechan",
    coricoriAlt: "Coricori",
    haramiAlt: "Harami",
    baraAlt: "Bara",
    cardHorumonTitle: "Horumon",
    cardHorumonText: "Variedad de horumon fresco para yakiniku o nabe.",
    cardBeefTitle: "Carne de res",
    cardBeefText: "Kalbi, harami, lengua y otros cortes ideales para yakiniku.",
    cardYorosuTitle: "Yorosu",
    cardYorosuText: "Corte de res/horumon con textura, ideal para yakiniku.",
    cardTechanTitle: "Techan",
    cardTechanText: "Horumon clásico con grasa sabrosa y buena mordida.",
    cardHosotechanTitle: "Hosotechan",
    cardHosotechanText: "Versión más fina de techan, fácil de asar y dorar.",
    cardCoricoriTitle: "Coricori",
    cardCoricoriText: "Corte de textura firme y crujiente, muy popular a la parrilla.",
    cardHaramiTitle: "Harami",
    cardHaramiText: "Corte de res intenso y jugoso, favorito para yakiniku.",
    cardBaraTitle: "Bara",
    cardBaraText: "Corte con buen balance de grasa y sabor para parrilla.",
    priceSpace: "Espacio para precio",
    askStore: "Consultar en tienda",
    priceKicker: "Precios",
    priceTitle: "Precios aproximados / 価格",
    priceIntro: "Los precios son editables. Completar con datos exactos antes de publicar.",
    priceAria: "Lista de precios",
    priceYorosu: "Yorosu",
    priceTechan: "Techan",
    priceHosotechan: "Hosotechan",
    priceCoricori: "Coricori",
    priceHarami: "Harami",
    priceBara: "Bara",
    priceNotice:
      "Los precios pueden cambiar según la disponibilidad. Para más detalles, consulta directamente con la tienda.",
    servicesKicker: "Servicios",
    servicesTitle: "Fácil de comprar, fácil de consultar.",
    serviceFresh: "Venta de carne fresca",
    serviceYakiniku: "Cortes para yakiniku",
    serviceBbq: "Preparación para BBQ",
    servicePeople: "Recomendación según personas",
    servicePhone: "Pedidos o consultas por teléfono",
    serviceStock: "Consulta de disponibilidad",
    serviceStore: "Atención en tienda",
    serviceInstagram: "Información diaria por Instagram",
    paymentKicker: "Métodos de pago",
    paymentTitle: "Esta información debe confirmarse antes de publicar.",
    paymentText:
      "Los métodos de pago distintos al efectivo deben confirmarse con la tienda antes de publicarlos como información definitiva.",
    cash: "Efectivo",
    confirmed: "Se puede publicar como confirmado",
    card: "Tarjeta",
    confirmBefore: "Confirmar antes de publicar",
    paypay: "PayPay / QR",
    otherPayment: "Otros",
    galleryKicker: "Fotos",
    galleryTitle: "Visuales limpios que hacen visible el producto.",
    galleryText:
      "Ahora se usan imágenes generadas para la web. Al publicar, pueden cambiarse por fotos reales de la tienda o fotos autorizadas de Instagram.",
    gallery1Alt: "Carnes para yakiniku en mostrador",
    gallery2Alt: "Surtido de horumon",
    gallery3Alt: "Cortes de res para yakiniku",
    gallery4Alt: "Set BBQ",
    gallery5Alt: "Imagen de tienda en Kyoto",
    gallery6Alt: "Mostrador de carnicería",
    howKicker: "Cómo comprar",
    howTitle: "Comprar es simple incluso si es tu primera vez.",
    step1Title: "Elige el uso",
    step1Text: "Yakiniku, BBQ, nabe, cena en casa.",
    step2Title: "Di cuántas personas",
    step2Text: "Así es más fácil recomendar la cantidad.",
    step3Title: "Consulta stock",
    step3Text: "Puedes llamar o preguntar en tienda.",
    step4Title: "Recoge en tienda",
    step4Text: "Retira carne fresca directamente en el local.",
    accessKicker: "Ubicación",
    accessTitle: "Cerca de Emmachi Station.",
    accessText:
      "Dirección: 京都市上京区丸太町御前東入る下之町400. Usa Google Maps para llegar desde tu ubicación actual.",
    addressLabel: "Dirección",
    mapTitle: "Google Maps - Nishida Horumon",
    faqKicker: "Preguntas frecuentes",
    faqTitle: "Lo útil antes de visitar.",
    faq1Q: "¿Se puede reservar o apartar producto?",
    faq1A: "Depende de la disponibilidad. Llama directamente a la tienda para confirmar.",
    faq2Q: "¿Pueden comprar turistas?",
    faq2A: "Sí. Es más fácil si explicas si quieres carne para yakiniku, BBQ o cocinar en casa.",
    faq3Q: "¿Los precios son siempre iguales?",
    faq3A: "Pueden cambiar según el abastecimiento. Confirma en tienda o por teléfono.",
    contactKicker: "Contacto",
    contactTitle: "Consulta antes de visitar.",
    telLabel: "Teléfono",
    openInstagram: "Abrir Instagram",
    openMaps: "Abrir Google Maps",
    floatingAria: "Acciones rápidas fijas",
    floatCall: "Llamar",
    footerSeo: "Horumon en Kyoto, carne para yakiniku y carnicería en Kamigyo-ku.",
    backTop: "Volver arriba",
  },
  en: {
    pageTitle: "Nishida Horumon | Japanese butcher shop in Kyoto",
    metaDescription:
      "Nishida Horumon in Kamigyo-ku, Kyoto. Local Japanese butcher shop specializing in beef, fresh horumon and yakiniku or BBQ cuts.",
    metaOgDescription: "Fresh Japanese meat and horumon in Kyoto.",
    brandAria: "Nishida Horumon home",
    navAria: "Main navigation",
    navAbout: "About",
    navMeat: "Meat",
    navPrices: "Prices",
    navAccess: "Access",
    languageLabel: "Language",
    languageAria: "Select language",
    callShort: "Call",
    heroAlt: "Display counter with yakiniku meat and horumon at Nishida Horumon",
    heroKicker: "Butcher shop in Kamigyo, Kyoto",
    heroTitle: "Fresh horumon and yakiniku meat in Kyoto",
    heroSubtitle: "Fresh Japanese meat and horumon in Kyoto",
    heroCopy: "For yakiniku, BBQ and home cooking. Fresh cuts prepared with care.",
    callNow: "Call now",
    viewInstagram: "View Instagram",
    viewMaps: "View location",
    storeInfoAria: "Store information",
    hoursLabel: "Hours",
    holidayLabel: "Closed",
    holidayValue: "No fixed closing day",
    stationLabel: "Nearby",
    stationValue: "Walking distance from Emmachi Station",
    quickAria: "Quick contact",
    quickPhoneLabel: "Phone",
    quickAddressLabel: "Address",
    addressShort: "Kamigyo-ku, Kyoto, Shimonochō 400",
    aboutKicker: "About",
    aboutTitle: "A trusted local butcher shop.",
    aboutText:
      "Nishida Horumon is a local butcher shop in Kamigyo-ku, Kyoto. The shop carefully prepares fresh horumon, yakiniku meat and convenient cuts for family cooking.",
    trustFresh: "Fresh meat",
    trustLocal: "Local Kyoto shop",
    trustYakiniku: "Yakiniku and BBQ",
    storefrontAlt: "Kyoto butcher shop image",
    showcaseAlt: "Meat display counter",
    recommendedAria: "Recommended today",
    bbqAlt: "Meat set for BBQ and yakiniku",
    dailyKicker: "Today's pick",
    dailyTitle: "If you are unsure, tell the shop how many people and what you are cooking.",
    dailyText:
      "Ask for recommendations for BBQ, yakiniku, nabe or dinner at home. Selection may change depending on supply.",
    askStock: "Check availability",
    meatKicker: "Products",
    meatTitle: "Beef and horumon cuts made for yakiniku.",
    horumonAlt: "Assorted horumon",
    beefAlt: "Beef cuts for yakiniku",
    yorosuAlt: "Yorosu",
    techanAlt: "Techan",
    hosotechanAlt: "Hosotechan",
    coricoriAlt: "Coricori",
    haramiAlt: "Harami",
    baraAlt: "Bara",
    cardHorumonTitle: "Horumon",
    cardHorumonText: "Fresh horumon varieties for yakiniku or nabe.",
    cardBeefTitle: "Beef",
    cardBeefText: "Kalbi, harami, tongue and other yakiniku-friendly cuts.",
    cardYorosuTitle: "Yorosu",
    cardYorosuText: "A textured beef horumon-style cut for yakiniku.",
    cardTechanTitle: "Techan",
    cardTechanText: "A classic horumon cut with rich fat and satisfying bite.",
    cardHosotechanTitle: "Hosotechan",
    cardHosotechanText: "A thinner techan cut that grills quickly and crisps nicely.",
    cardCoricoriTitle: "Coricori",
    cardCoricoriText: "A firm, crunchy cut prized for its texture on the grill.",
    cardHaramiTitle: "Harami",
    cardHaramiText: "A flavorful, juicy beef cut and yakiniku favorite.",
    cardBaraTitle: "Bara",
    cardBaraText: "A grill-friendly beef cut with rich fat and savory flavor.",
    priceSpace: "Price space",
    askStore: "Ask in store",
    priceKicker: "Prices",
    priceTitle: "Estimated prices / 価格",
    priceIntro: "Price fields are editable. Add exact prices before publishing.",
    priceAria: "Price list",
    priceYorosu: "Yorosu",
    priceTechan: "Techan",
    priceHosotechan: "Hosotechan",
    priceCoricori: "Coricori",
    priceHarami: "Harami",
    priceBara: "Bara",
    priceNotice:
      "Prices may change depending on supply. Please contact the shop for details.",
    servicesKicker: "Services",
    servicesTitle: "Easy to buy, easy to ask.",
    serviceFresh: "Fresh meat sales",
    serviceYakiniku: "Yakiniku cuts",
    serviceBbq: "BBQ preparation",
    servicePeople: "Recommendations by group size",
    servicePhone: "Phone orders and questions",
    serviceStock: "Availability check",
    serviceStore: "In-store support",
    serviceInstagram: "Daily information on Instagram",
    paymentKicker: "Payment",
    paymentTitle: "Confirm this before publishing.",
    paymentText:
      "Payment methods other than cash should be confirmed with the shop before listing them as final information.",
    cash: "Cash",
    confirmed: "Can be listed as confirmed",
    card: "Card",
    confirmBefore: "Confirm before publishing",
    paypay: "PayPay / QR",
    otherPayment: "Other",
    galleryKicker: "Photos",
    galleryTitle: "Clean visuals that make the product clear.",
    galleryText:
      "The current site uses generated web visuals. Before publishing, they can be replaced with real shop photos or approved Instagram images.",
    gallery1Alt: "Yakiniku meat in a display counter",
    gallery2Alt: "Assorted horumon",
    gallery3Alt: "Beef cuts for yakiniku",
    gallery4Alt: "BBQ set",
    gallery5Alt: "Kyoto shop image",
    gallery6Alt: "Butcher shop display counter",
    howKicker: "How to buy",
    howTitle: "Simple, even on your first visit.",
    step1Title: "Choose the use",
    step1Text: "Yakiniku, BBQ, nabe or dinner at home.",
    step2Title: "Say the group size",
    step2Text: "This makes it easier to recommend the right amount.",
    step3Title: "Check stock",
    step3Text: "Call or ask directly in store.",
    step4Title: "Pick up",
    step4Text: "Collect fresh meat directly at the shop.",
    accessKicker: "Access",
    accessTitle: "Near Emmachi Station.",
    accessText:
      "Address: 京都市上京区丸太町御前東入る下之町400. Use Google Maps to get directions from your current location.",
    addressLabel: "Address",
    mapTitle: "Google Maps - Nishida Horumon",
    faqKicker: "FAQ",
    faqTitle: "Useful details before visiting.",
    faq1Q: "Can I reserve or hold items?",
    faq1A: "It depends on availability. Please call the shop directly to confirm.",
    faq2Q: "Can tourists shop here?",
    faq2A: "Yes. It helps to explain whether you need meat for yakiniku, BBQ or home cooking.",
    faq3Q: "Are prices always the same?",
    faq3A: "Prices may change depending on supply. Please confirm in store or by phone.",
    contactKicker: "Contact",
    contactTitle: "Check before you visit.",
    telLabel: "Phone",
    openInstagram: "Open Instagram",
    openMaps: "Open Google Maps",
    floatingAria: "Fixed quick actions",
    floatCall: "Call",
    footerSeo: "Kyoto horumon, yakiniku meat and butcher shop in Kamigyo-ku.",
    backTop: "Back to top",
  },
};

const header = document.querySelector(".site-header");
const languageSelect = document.querySelector("#language-select");
const floatingActions = document.querySelector(".floating-actions");

function setHeaderState() {
  header.dataset.elevated = window.scrollY > 18 ? "true" : "false";
  floatingActions.dataset.visible = window.scrollY > 560 ? "true" : "false";
}

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations.ja;
  document.documentElement.lang = lang;
  document.title = dictionary.pageTitle;

  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) node.textContent = dictionary[key];
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((node) => {
    node.dataset.i18nAttr.split(",").forEach((pair) => {
      const [attribute, key] = pair.split(":").map((part) => part.trim());
      if (attribute && key && dictionary[key]) {
        node.setAttribute(attribute, dictionary[key]);
      }
    });
  });

  window.localStorage.setItem("nishida-language", lang);
}

window.addEventListener("scroll", setHeaderState, { passive: true });
languageSelect.addEventListener("change", (event) => applyLanguage(event.target.value));

const savedLanguage = window.localStorage.getItem("nishida-language");
const browserLanguage = (navigator.language || "ja").slice(0, 2);
const initialLanguage = savedLanguage || (translations[browserLanguage] ? browserLanguage : "ja");

languageSelect.value = initialLanguage;
applyLanguage(initialLanguage);
setHeaderState();
